#!/bin/bash
#
# Original script by fornesia, rzengineer and fawzya
# Mod by Bustami Arifin
# Translation by _PakTam_
# ==================================================

# Initializing Var
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";

# Details of _PakTam_
country=MY
state=Kuala_Lumpur
locality=Kuala_Lumpur
organization=Bystander
organizationalunit=Bystander
commonname=Bystander
email=arelift.sgs4@gmail.com

# go to root
cd

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local

# install wget and curl
apt-get update;apt-get -y install wget curl;

# set time GMT +8
ln -fs /usr/share/zoneinfo/Asia/Kuala_Lumpur /etc/localtime

# set locale
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service ssh restart

# set repo
wget -O /etc/apt/sources.list "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/sources.list.debian7"
wget "http://www.dotdeb.org/dotdeb.gpg"
cat dotdeb.gpg | apt-key add -;rm dotdeb.gpg
sh -c 'echo "deb http://download.webmin.com/download/repository sarge contrib" > /etc/apt/sources.list.d/webmin.list'
wget -qO - http://www.webmin.com/jcameron-key.asc | apt-key add -

# update
apt-get update

# install webserver
apt-get -y install nginx

# install essential package
apt-get -y install nano iptables dnsutils openvpn screen whois ngrep unzip unrar

# setting port ssh
cd
sed -i 's/Port 22/Port 22/g' /etc/ssh/sshd_config
sed -i '/Port 22/a Port 444' /etc/ssh/sshd_config
service ssh restart

# install dropbear
apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=443/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 80"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
service ssh restart
service dropbear restart

# install squid3
cd
apt-get -y install squid3
wget -O /etc/squid3/squid.conf "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/squid3.conf"
sed -i $MYIP2 /etc/squid3/squid.conf;
service squid3 restart

# install webmin
cd
apt-get -y install webmin
sed -i 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
service webmin restart

# install stunnel
apt-get install stunnel4 -y
cat > /etc/stunnel/stunnel.conf <<-END
cert = /etc/stunnel/stunnel.pem
client = no
socket = a:SO_REUSEADDR=1
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1


[dropbear]
accept = 143
connect = 127.0.0.1:443

END

# install fail2ban
apt-get -y install fail2ban;
service fail2ban restart

# install ddos deflate
cd
apt-get -y install dnsutils dsniff
wget https://github.com/PakTam/Deb7AutoScriptVPS/raw/master/ddos-deflate-master.zip
unzip ddos-deflate-master.zip
cd ddos-deflate-master
./install.sh
rm -rf /root/ddos-deflate-master.zip

# banner
rm /etc/issue.net
wget -O /etc/issue.net "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/issue.net"
sed -i 's@#Banner@Banner@g' /etc/ssh/sshd_config
sed -i 's@DROPBEAR_BANNER=""@DROPBEAR_BANNER="/etc/issue.net"@g' /etc/default/dropbear
service ssh restart
service dropbear restart

#xml parser
cd
apt-get -y --force-yes -f install libxml-parser-perl

# download script
cd /usr/bin
wget -O menu "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/menu.sh"
wget -O add "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/usernew.sh"
wget -O trial "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/trial.sh"
wget -O remove "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/hapus.sh"
wget -O check "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/user-login.sh"
wget -O member "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/user-list.sh"
wget -O banner "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/servermessage.sh"
wget -O restart "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/resvis.sh"
wget -O speedtest "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/speedtest_cli.py"
wget -O info "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/info.sh"
wget -O about "https://raw.githubusercontent.com/PakTam/Deb7AutoScriptVPS/master/about.sh"

echo "0 0 * * * root /sbin/reboot" > /etc/cron.d/reboot

chmod +x menu
chmod +x add
chmod +x trial
chmod +x remove
chmod +x check
chmod +x member
chmod +x banner
chmod +x restart
chmod +x speedtest
chmod +x info
chmod +x about

# finishing
cd
chown -R www-data:www-data /home/vps/public_html
service nginx start
service openvpn restart
service cron restart
service ssh restart
service dropbear restart
service squid3 restart
service webmin restart
rm -rf ~/.bash_history && history -c
echo "unset HISTFILE" >> /etc/profile

# install neofetch
echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | tee -a /etc/apt/sources.list
curl "https://bintray.com/user/downloadSubjectPublicKey?username=bintray"| apt-key add -
apt-get update
apt-get install neofetch

echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | tee -a /etc/apt/sources.list
curl "https://bintray.com/user/downloadSubjectPublicKey?username=bintray"| apt-key add -
apt-get update
apt-get install neofetch

# info
clear
echo "Deb7AutoScriptVPS Includes:" | tee log-install.txt
echo "===========================================" | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Service"  | tee -a log-install.txt
echo "-------"  | tee -a log-install.txt
echo "OpenSSH  : 22, 444"  | tee -a log-install.txt
echo "Dropbear : 80, 443"  | tee -a log-install.txt
echo "SSL      : 143"  | tee -a log-install.txt
echo "Squid3   : 8000, 8080 (limit to IP SSH)"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Commands"  | tee -a log-install.txt
echo "------"  | tee -a log-install.txt
echo "menu       (Show Commands)"  | tee -a log-install.txt
echo "add        (Create User Account)"  | tee -a log-install.txt
echo "trial      (Create Trial Account)"  | tee -a log-install.txt
echo "remove     (Remove User Account)"  | tee -a log-install.txt
echo "check      (Check User Login)"  | tee -a log-install.txt
echo "member     (Check Member)"  | tee -a log-install.txt
echo "banner     (Configure Server Message)"  | tee -a log-install.txt
echo "restart    (Restart Service Dropbear, Webmin,"  | tee -a log-install.txt
echo "            Squid3, Openvpn and SSH)"  | tee -a log-install.txt
echo "reboot     (Reboot VPS)"  | tee -a log-install.txt
echo "speedtest  (Speedtest VPS)"  | tee -a log-install.txt
echo "info       (System Information)"  | tee -a log-install.txt
echo "about      (Debian AutoScript VPS Info)"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Other Features"  | tee -a log-install.txt
echo "----------"  | tee -a log-install.txt
echo "DDoS Deflate   : Anti-DDOS"  | tee -a log-install.txt
echo "OCS Panel      : Supported"  | tee -a log-install.txt
echo "Webmin         : http://$MYIP:10000/"  | tee -a log-install.txt
echo "Timezone       : Asia/Kuala_Lumpur (GMT +8)"  | tee -a log-install.txt
echo "IPv6           : [off]"  | tee -a log-install.txt

echo ""  | tee -a log-install.txt
echo "Original Script by Fornesia, Rzengineer & Fawzya"  | tee -a log-install.txt
echo "Modified by Bustami Arifin"  | tee -a log-install.txt
echo "Translation by _PakTam_"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Installation Logs --> /root/log-install.txt"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "VPS Auto Reboot at 12 AM"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "==========================================="  | tee -a log-install.txt
cd
rm -f /root/debian7.sh
